language: cpp

env:
  global:
  # Ubuntu version
  - LINUX_DIST=trusty
  - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
  # Global build options and C++ flags
  - CXX_FLAGS="-Wall -pedantic -Werror -Wno-variadic-macros -Wno-long-long -Wno-shadow"
  # Misc
  - RUN_TESTS=true
  - COVERAGE=false

matrix:
  include:
  - os: linux
    dist: trusty
    sudo: true
    compiler: gcc
    addons:
      apt:
        packages:
        - gcc-4.8
        - g++-4.8
        #- gcov-4.9
        - clang-3.7
        - valgrind

script:
############################################################################
# Build main and tests
############################################################################
- mkdir -p build
- cd build
- cmake ${CMAKE_OPTIONS} -DCMAKE_CXX_FLAGS=${CXX_FLAGS} -DCMAKE_BUILD_TYPE=Coverage -DCPX_ENABLE_TEST=ON ..
- make
- make test
